### ISSUE TITLE
Flickering subtitles & epg info text on uclan ustym 4k pro

### ISSUE THREAD

**Issue by imperia777** [OpenPLi-meta/meta-uclan#1]
Subtitles & EPG info text is flickering on Uclan ustym 4k pro.

I am attaching samples:

https://youtu.be/GzfeP12QdWU

https://youtu.be/WyvsbQ5PC4U

More information in this thread:

https://forums.openpli.org/topic/90804-flickering-subtitles-epg-info-text-on-uclan-ustym-4k-pro/

**Comment by WanWizard** [comment]
Since there is a forum thread, closed this issue.
